import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import FooterData from "@/lib/types/FooterData";
import MenuItem from "@/lib/types/MenuItem";
import InfoData from "@/lib/types/InfoData";

const Layout = (
  {
    children,
    footer,
    menu,
    info,
    title
  } : {
    children: JSX.Element | JSX.Element[] | null,
    footer: FooterData,
    menu: MenuItem[],
    info: InfoData,
    title: string
  }
) => {
  return (
    <>
      <Head>
        <title>{`${title} | ${info.companyName + (info.slogan !== "" ? " | "+info.slogan : "")}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header menu={menu} logo={footer.logo}/>
      <main>{children}</main>
      <Footer footerData={footer} info={info} />
    </>
  );
};

export default Layout;
